# Generated by Django 4.1.7 on 2023-03-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paslaugos", "0002_uzsakymas_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="automobilis",
            name="defektai",
            field=models.TextField(default="", max_length=2500),
        ),
        migrations.AddField(
            model_name="paslauga",
            name="aprasymas",
            field=models.TextField(default="", max_length=5000),
        ),
    ]
