# Generated by Django 4.1.7 on 2023-03-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paslaugos", "0003_automobilis_defektai_paslauga_aprasymas"),
    ]

    operations = [
        migrations.AddField(
            model_name="automobilis",
            name="virselis",
            field=models.ImageField(null=True, upload_to="covers"),
        ),
    ]
