# Generated by Django 4.1.7 on 2023-03-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paslaugos", "0004_automobilis_virselis"),
    ]

    operations = [
        migrations.AddField(
            model_name="automobiliomodelis",
            name="virselis",
            field=models.ImageField(null=True, upload_to="virseliai"),
        ),
    ]
