# Generated by Django 4.1.7 on 2023-03-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paslaugos", "0006_rename_virselis_automobiliomodelis_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="automobiliomodelis",
            name="photo",
        ),
    ]
